---
version: "3"
services:
 devopsdb:
   image: naresh007007/java:db
   ports:
     - "3306:3306"

 application:
   image: naresh007007/java:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
